version: "3.3"

services:
  postgres:
    image: postgres
    container_name: database
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: login
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/pgdata:/var/lib/postgresql/data
    expose:
      - 5432

  microservice:
    build:
      dockerfile: ./microservice/Dockerfile
      context: .
    image: login-microservice
    container_name: microservice
    volumes:
      - .:/project/login
    ports:
      - 4000:4000
    depends_on:
      - postgres
